In [2]:
import numpy as np
import pandas as pd
import warnings 
from rich import pretty
pretty.install()
warnings.filterwarnings('ignore')

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)['cast'].values[0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [5]:
print(movies.shape)
print(credits.shape)

(4803, 20)
(4803, 4)

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.shape

(4809, 23)

In [8]:
movies.original_language.value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ar       2
id       2
ro       2
te       1
xx       1
hu       1
is       1
tr       1
nb       1
af       1
pl       1
vi       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

##### Original language is also a good column for recommendation but since the data is very imbalanced more skewed towards en (english) movies. We may drop this.

In [9]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [10]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
# For data precprocessing removing null and duplicate data, if any

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.duplicated().sum()

np.int64(0)

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
# converting the given list of Dict into list of strings ['Action','Fantasy','Adventure'...]
from ast import literal_eval

def convert(obj):
    array = []
    for i in literal_eval(obj):
        array.append(i['name'])
    
    return array

In [18]:
convert(movies.iloc[0].genres)

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [19]:
movies['genres'] = movies['genres'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
# Similarly, doing the same for keywords (having same key -> name)

movies['keywords'] = movies['keywords'].apply(convert)

In [22]:
movies.iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres          [Action, Adventure, Fantasy, Science Fiction]
keywords    [culture clash, future, space war, space colon...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [23]:
# Creating a fn for cast and crew
def convert_for_cast(obj):
    counter = 0
    array = []
    for i in literal_eval(obj):
        if counter != 3:
            array.append(i['name'])
            counter += 1
        else :
            break
    return array

In [24]:
convert_for_cast(movies.iloc[0].cast)

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [25]:
movies['cast'] = movies['cast'].apply(convert_for_cast)

In [26]:
movies.iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres          [Action, Adventure, Fantasy, Science Fiction]
keywords    [culture clash, future, space war, space colon...
cast         [Sam Worthington, Zoe Saldana, Sigourney Weaver]
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [27]:
literal_eval(movies.crew[0])
# since for a movie one of the most important aspect (apart from cast) is the director and we filter out the director name

[
    {
        'credit_id': '52fe48009251416c750aca23',
        'department': 'Editing',
        'gender': 0,
        'id': 1721,
        'job': 'Editor',
        'name': 'Stephen E. Rivkin'
    },
    {
        'credit_id': '539c47ecc3a36810e3001f87',
        'department': 'Art',
        'gender': 2,
        'id': 496,
        'job': 'Production Design',
        'name': 'Rick Carter'
    },
    {
        'credit_id': '54491c89c3a3680fb4001cf7',
        'department': 'Sound',
        'gender': 0,
        'id': 900,
        'job': 'Sound Designer',
        'name': 'Christopher Boyes'
    },
    {
        'credit_id': '54491cb70e0a267480001bd0',
        'department': 'Sound',
        'gender': 0,
        'id': 900,
        'job': 'Supervising Sound Editor',
        'name': 'Christopher Boyes'
    },
    {
        'credit_id': '539c4a4cc3a36810c9002101',
        'department': 'Production',
        'gender': 1,
        'id': 1262,
        'job': 'Casting',
        'name': 'Mali Finn'
    },
    {
        'credit_id': '5544ee3b925141499f0008fc',
        'department': 'Sound',
        'gender': 2,
        'id': 1729,
        'job': 'Original Music Composer',
        'name': 'James Horner'
    },
    {
        'credit_id': '52fe48009251416c750ac9c3',
        'department': 'Directing',
        'gender': 2,
        'id': 2710,
        'job': 'Director',
        'name': 'James Cameron'
    },
    {
        'credit_id': '52fe48009251416c750ac9d9',
        'department': 'Writing',
        'gender': 2,
        'id': 2710,
        'job': 'Writer',
        'name': 'James Cameron'
    },
    {
        'credit_id': '52fe48009251416c750aca17',
        'department': 'Editing',
        'gender': 2,
        'id': 2710,
        'job': 'Editor',
        'name': 'James Cameron'
    },
    {
        'credit_id': '52fe48009251416c750aca29',
        'department': 'Production',
        'gender': 2,
        'id': 2710,
        'job': 'Producer',
        'name': 'James Cameron'
    },
    {
        'credit_id': '52fe48009251416c750aca3f',
        'department': 'Writing',
        'gender': 2,
        'id': 2710,
        'job': 'Screenplay',
        'name': 'James Cameron'
    },
    {
        'credit_id': '539c4987c3a36810ba0021a4',
        'department': 'Art',
        'gender': 2,
        'id': 7236,
        'job': 'Art Direction',
        'name': 'Andrew Menzies'
    },
    {
        'credit_id': '549598c3c3a3686ae9004383',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 6690,
        'job': 'Visual Effects Producer',
        'name': 'Jill Brooks'
    },
    {
        'credit_id': '52fe48009251416c750aca4b',
        'department': 'Production',
        'gender': 1,
        'id': 6347,
        'job': 'Casting',
        'name': 'Margery Simkin'
    },
    {
        'credit_id': '570b6f419251417da70032fe',
        'department': 'Art',
        'gender': 2,
        'id': 6878,
        'job': 'Supervising Art Director',
        'name': 'Kevin Ishioka'
    },
    {
        'credit_id': '5495a0fac3a3686ae9004468',
        'department': 'Sound',
        'gender': 0,
        'id': 6883,
        'job': 'Music Editor',
        'name': 'Dick Bernstein'
    },
    {
        'credit_id': '54959706c3a3686af3003e81',
        'department': 'Sound',
        'gender': 0,
        'id': 8159,
        'job': 'Sound Effects Editor',
        'name': 'Shannon Mills'
    },
    {
        'credit_id': '54491d58c3a3680fb1001ccb',
        'department': 'Sound',
        'gender': 0,
        'id': 8160,
        'job': 'Foley',
        'name': 'Dennie Thorpe'
    },
    {
        'credit_id': '54491d6cc3a3680fa5001b2c',
        'department': 'Sound',
        'gender': 0,
        'id': 8163,
        'job': 'Foley',
        'name': 'Jana Vance'
    },
    {
        'credit_id': '52fe48009251416c750aca57',
        'department': 'Costume & Make-Up',
        'gender': 1,
        'id': 8527,
        'job': 'Costume Design',
        'name': 'Deborah Lynn Scott'
    },
    {
        'credit_id': '52fe48009251416c750aca2f',
        'department': 'Production',
        'gender': 2,
        'id': 8529,
        'job': 'Producer',
        'name': 'Jon Landau'
    },
    {
        'credit_id': '539c4937c3a36810ba002194',
        'department': 'Art',
        'gender': 0,
        'id': 9618,
        'job': 'Art Direction',
        'name': 'Sean Haworth'
    },
    {
        'credit_id': '539c49b6c3a36810c10020e6',
        'department': 'Art',
        'gender': 1,
        'id': 12653,
        'job': 'Set Decoration',
        'name': 'Kim Sinclair'
    },
    {
        'credit_id': '570b6f2f9251413a0e00020d',
        'department': 'Art',
        'gender': 1,
        'id': 12653,
        'job': 'Supervising Art Director',
        'name': 'Kim Sinclair'
    },
    {
        'credit_id': '54491a6c0e0a26748c001b19',
        'department': 'Art',
        'gender': 2,
        'id': 14350,
        'job': 'Set Designer',
        'name': 'Richard F. Mays'
    },
    {
        'credit_id': '56928cf4c3a3684cff0025c4',
        'department': 'Production',
        'gender': 1,
        'id': 20294,
        'job': 'Executive Producer',
        'name': 'Laeta Kalogridis'
    },
    {
        'credit_id': '52fe48009251416c750aca51',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 17675,
        'job': 'Costume Design',
        'name': 'Mayes C. Rubeo'
    },
    {
        'credit_id': '52fe48009251416c750aca11',
        'department': 'Camera',
        'gender': 2,
        'id': 18265,
        'job': 'Director of Photography',
        'name': 'Mauro Fiore'
    },
    {
        'credit_id': '5449194d0e0a26748f001b39',
        'department': 'Art',
        'gender': 0,
        'id': 42281,
        'job': 'Set Designer',
        'name': 'Scott Herbertson'
    },
    {
        'credit_id': '52fe48009251416c750aca05',
        'department': 'Crew',
        'gender': 0,
        'id': 42288,
        'job': 'Stunts',
        'name': 'Woody Schultz'
    },
    {
        'credit_id': '5592aefb92514152de0010f5',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 29067,
        'job': 'Makeup Artist',
        'name': 'Linda DeVetta'
    },
    {
        'credit_id': '5592afa492514152de00112c',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 29067,
        'job': 'Hairstylist',
        'name': 'Linda DeVetta'
    },
    {
        'credit_id': '54959ed592514130fc002e5d',
        'department': 'Camera',
        'gender': 2,
        'id': 33302,
        'job': 'Camera Operator',
        'name': 'Richard Bluck'
    },
    {
        'credit_id': '539c4891c3a36810ba002147',
        'department': 'Art',
        'gender': 2,
        'id': 33303,
        'job': 'Art Direction',
        'name': 'Simon Bright'
    },
    {
        'credit_id': '54959c069251417a81001f3a',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 113145,
        'job': 'Visual Effects Supervisor',
        'name': 'Richard Martin'
    },
    {
        'credit_id': '54959a0dc3a3680ff5002c8d',
        'department': 'Crew',
        'gender': 2,
        'id': 58188,
        'job': 'Visual Effects Editor',
        'name': 'Steve R. Moore'
    },
    {
        'credit_id': '52fe48009251416c750aca1d',
        'department': 'Editing',
        'gender': 2,
        'id': 58871,
        'job': 'Editor',
        'name': 'John Refoua'
    },
    {
        'credit_id': '54491a4dc3a3680fc30018ca',
        'department': 'Art',
        'gender': 0,
        'id': 92359,
        'job': 'Set Designer',
        'name': 'Karl J. Martin'
    },
    {
        'credit_id': '52fe48009251416c750aca35',
        'department': 'Camera',
        'gender': 1,
        'id': 72201,
        'job': 'Director of Photography',
        'name': 'Chiling Lin'
    },
    {
        'credit_id': '52fe48009251416c750ac9ff',
        'department': 'Crew',
        'gender': 0,
        'id': 89714,
        'job': 'Stunts',
        'name': 'Ilram Choi'
    },
    {
        'credit_id': '54959c529251416e2b004394',
        'department': 'Visual Effects',
        'gender': 2,
        'id': 93214,
        'job': 'Visual Effects Supervisor',
        'name': 'Steven Quale'
    },
    {
        'credit_id': '54491edf0e0a267489001c37',
        'department': 'Crew',
        'gender': 1,
        'id': 122607,
        'job': 'Dialect Coach',
        'name': 'Carla Meyer'
    },
    {
        'credit_id': '539c485bc3a368653d001a3a',
        'department': 'Art',
        'gender': 2,
        'id': 132585,
        'job': 'Art Direction',
        'name': 'Nick Bassett'
    },
    {
        'credit_id': '539c4903c3a368653d001a74',
        'department': 'Art',
        'gender': 0,
        'id': 132596,
        'job': 'Art Direction',
        'name': 'Jill Cormack'
    },
    {
        'credit_id': '539c4967c3a368653d001a94',
        'department': 'Art',
        'gender': 0,
        'id': 132604,
        'job': 'Art Direction',
        'name': 'Andy McLaren'
    },
    {
        'credit_id': '52fe48009251416c750aca45',
        'department': 'Crew',
        'gender': 0,
        'id': 236696,
        'job': 'Motion Capture Artist',
        'name': 'Terry Notary'
    },
    {
        'credit_id': '54959e02c3a3680fc60027d2',
        'department': 'Crew',
        'gender': 2,
        'id': 956198,
        'job': 'Stunt Coordinator',
        'name': 'Garrett Warren'
    },
    {
        'credit_id': '54959ca3c3a3686ae300438c',
        'department': 'Visual Effects',
        'gender': 2,
        'id': 957874,
        'job': 'Visual Effects Supervisor',
        'name': 'Jonathan Rothbart'
    },
    {
        'credit_id': '570b6f519251412c74001b2f',
        'department': 'Art',
        'gender': 0,
        'id': 957889,
        'job': 'Supervising Art Director',
        'name': 'Stefan Dechant'
    },
    {
        'credit_id': '570b6f62c3a3680b77007460',
        'department': 'Art',
        'gender': 2,
        'id': 959555,
        'job': 'Supervising Art Director',
        'name': 'Todd Cherniawsky'
    },
    {
        'credit_id': '539c4a3ac3a36810da0021cc',
        'department': 'Production',
        'gender': 0,
        'id': 1016177,
        'job': 'Casting',
        'name': 'Miranda Rivers'
    },
    {
        'credit_id': '539c482cc3a36810c1002062',
        'department': 'Art',
        'gender': 0,
        'id': 1032536,
        'job': 'Production Design',
        'name': 'Robert Stromberg'
    },
    {
        'credit_id': '539c4b65c3a36810c9002125',
        'department': 'Costume & Make-Up',
        'gender': 2,
        'id': 1071680,
        'job': 'Costume Design',
        'name': 'John Harding'
    },
    {
        'credit_id': '54959e6692514130fc002e4e',
        'department': 'Camera',
        'gender': 0,
        'id': 1177364,
        'job': 'Steadicam Operator',
        'name': 'Roberto De Angelis'
    },
    {
        'credit_id': '539c49f1c3a368653d001aac',
        'department': 'Costume & Make-Up',
        'gender': 2,
        'id': 1202850,
        'job': 'Makeup Department Head',
        'name': 'Mike Smithson'
    },
    {
        'credit_id': '5495999ec3a3686ae100460c',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1204668,
        'job': 'Visual Effects Producer',
        'name': 'Alain Lalanne'
    },
    {
        'credit_id': '54959cdfc3a3681153002729',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1206410,
        'job': 'Visual Effects Supervisor',
        'name': 'Lucas Salton'
    },
    {
        'credit_id': '549596239251417a81001eae',
        'department': 'Crew',
        'gender': 0,
        'id': 1234266,
        'job': 'Post Production Supervisor',
        'name': 'Janace Tashjian'
    },
    {
        'credit_id': '54959c859251416e1e003efe',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1271932,
        'job': 'Visual Effects Supervisor',
        'name': 'Stephen Rosenbaum'
    },
    {
        'credit_id': '5592af28c3a368775a00105f',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 1310064,
        'job': 'Makeup Artist',
        'name': 'Frankie Karena'
    },
    {
        'credit_id': '539c4adfc3a36810e300203b',
        'department': 'Costume & Make-Up',
        'gender': 1,
        'id': 1319844,
        'job': 'Costume Supervisor',
        'name': 'Lisa Lovaas'
    },
    {
        'credit_id': '54959b579251416e2b004371',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1327028,
        'job': 'Visual Effects Supervisor',
        'name': 'Jonathan Fawkner'
    },
    {
        'credit_id': '539c48a7c3a36810b5001fa7',
        'department': 'Art',
        'gender': 0,
        'id': 1330561,
        'job': 'Art Direction',
        'name': 'Robert Bavin'
    },
    {
        'credit_id': '539c4a71c3a36810da0021e0',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 1330567,
        'job': 'Costume Supervisor',
        'name': 'Anthony Almaraz'
    },
    {
        'credit_id': '539c4a8ac3a36810ba0021e4',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 1330570,
        'job': 'Costume Supervisor',
        'name': 'Carolyn M. Fenton'
    },
    {
        'credit_id': '539c4ab6c3a36810da0021f0',
        'department': 'Costume & Make-Up',
        'gender': 0,
        'id': 1330574,
        'job': 'Costume Supervisor',
        'name': 'Beth Koenigsberg'
    },
    {
        'credit_id': '54491ab70e0a267480001ba2',
        'department': 'Art',
        'gender': 0,
        'id': 1336191,
        'job': 'Set Designer',
        'name': 'Sam Page'
    },
    {
        'credit_id': '544919d9c3a3680fc30018bd',
        'department': 'Art',
        'gender': 0,
        'id': 1339441,
        'job': 'Set Designer',
        'name': 'Tex Kadonaga'
    },
    {
        'credit_id': '54491cf50e0a267483001b0c',
        'department': 'Editing',
        'gender': 0,
        'id': 1352422,
        'job': 'Dialogue Editor',
        'name': 'Kim Foscato'
    },
    {
        'credit_id': '544919f40e0a26748c001b09',
        'department': 'Art',
        'gender': 0,
        'id': 1352962,
        'job': 'Set Designer',
        'name': 'Tammy S. Lee'
    },
    {
        'credit_id': '5495a115c3a3680ff5002d71',
        'department': 'Crew',
        'gender': 0,
        'id': 1357070,
        'job': 'Transportation Coordinator',
        'name': 'Denny Caira'
    },
    {
        'credit_id': '5495a12f92514130fc002e94',
        'department': 'Crew',
        'gender': 0,
        'id': 1357071,
        'job': 'Transportation Coordinator',
        'name': 'James Waitkus'
    },
    {
        'credit_id': '5495976fc3a36811530026b0',
        'department': 'Sound',
        'gender': 0,
        'id': 1360103,
        'job': 'Supervising Sound Editor',
        'name': 'Addison Teague'
    },
    {
        'credit_id': '54491837c3a3680fb1001c5a',
        'department': 'Art',
        'gender': 2,
        'id': 1376887,
        'job': 'Set Designer',
        'name': 'C. Scott Baker'
    },
    {
        'credit_id': '54491878c3a3680fb4001c9d',
        'department': 'Art',
        'gender': 0,
        'id': 1376888,
        'job': 'Set Designer',
        'name': 'Luke Caska'
    },
    {
        'credit_id': '544918dac3a3680fa5001ae0',
        'department': 'Art',
        'gender': 0,
        'id': 1376889,
        'job': 'Set Designer',
        'name': 'David Chow'
    },
    {
        'credit_id': '544919110e0a267486001b68',
        'department': 'Art',
        'gender': 0,
        'id': 1376890,
        'job': 'Set Designer',
        'name': 'Jonathan Dyer'
    },
    {
        'credit_id': '54491967c3a3680faa001b5e',
        'department': 'Art',
        'gender': 0,
        'id': 1376891,
        'job': 'Set Designer',
        'name': 'Joseph Hiura'
    },
    {
        'credit_id': '54491997c3a3680fb1001c8a',
        'department': 'Art',
        'gender': 0,
        'id': 1376892,
        'job': 'Art Department Coordinator',
        'name': 'Rebecca Jellie'
    },
    {
        'credit_id': '544919ba0e0a26748f001b42',
        'department': 'Art',
        'gender': 0,
        'id': 1376893,
        'job': 'Set Designer',
        'name': 'Robert Andrew Johnson'
    },
    {
        'credit_id': '54491b1dc3a3680faa001b8c',
        'department': 'Art',
        'gender': 0,
        'id': 1376895,
        'job': 'Assistant Art Director',
        'name': 'Mike Stassi'
    },
    {
        'credit_id': '54491b79c3a3680fbb001826',
        'department': 'Art',
        'gender': 0,
        'id': 1376897,
        'job': 'Construction Coordinator',
        'name': 'John Villarino'
    },
    {
        'credit_id': '54491baec3a3680fb4001ce6',
        'department': 'Art',
        'gender': 2,
        'id': 1376898,
        'job': 'Assistant Art Director',
        'name': 'Jeffrey Wisniewski'
    },
    {
        'credit_id': '54491d2fc3a3680fb4001d07',
        'department': 'Editing',
        'gender': 0,
        'id': 1376899,
        'job': 'Dialogue Editor',
        'name': 'Cheryl Nardi'
    },
    {
        'credit_id': '54491d86c3a3680fa5001b2f',
        'department': 'Editing',
        'gender': 0,
        'id': 1376901,
        'job': 'Dialogue Editor',
        'name': 'Marshall Winn'
    },
    {
        'credit_id': '54491d9dc3a3680faa001bb0',
        'department': 'Sound',
        'gender': 0,
        'id': 1376902,
        'job': 'Supervising Sound Editor',
        'name': 'Gwendolyn Yates Whittle'
    },
    {
        'credit_id': '54491dc10e0a267486001bce',
        'department': 'Sound',
        'gender': 0,
        'id': 1376903,
        'job': 'Sound Re-Recording Mixer',
        'name': 'William Stein'
    },
    {
        'credit_id': '54491f500e0a26747c001c07',
        'department': 'Crew',
        'gender': 0,
        'id': 1376909,
        'job': 'Choreographer',
        'name': 'Lula Washington'
    },
    {
        'credit_id': '549599239251412c4e002a2e',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1391692,
        'job': 'Visual Effects Producer',
        'name': 'Chris Del Conte'
    },
    {
        'credit_id': '54959d54c3a36831b8001d9a',
        'department': 'Visual Effects',
        'gender': 2,
        'id': 1391695,
        'job': 'Visual Effects Supervisor',
        'name': 'R. Christopher White'
    },
    {
        'credit_id': '54959bdf9251412c4e002a66',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1394070,
        'job': 'Visual Effects Supervisor',
        'name': 'Dan Lemmon'
    },
    {
        'credit_id': '5495971d92514132ed002922',
        'department': 'Sound',
        'gender': 0,
        'id': 1394129,
        'job': 'Sound Effects Editor',
        'name': 'Tim Nielsen'
    },
    {
        'credit_id': '5592b25792514152cc0011aa',
        'department': 'Crew',
        'gender': 0,
        'id': 1394286,
        'job': 'CG Supervisor',
        'name': 'Michael Mulholland'
    },
    {
        'credit_id': '54959a329251416e2b004355',
        'department': 'Crew',
        'gender': 0,
        'id': 1394750,
        'job': 'Visual Effects Editor',
        'name': 'Thomas Nittmann'
    },
    {
        'credit_id': '54959d6dc3a3686ae9004401',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1394755,
        'job': 'Visual Effects Supervisor',
        'name': 'Edson Williams'
    },
    {
        'credit_id': '5495a08fc3a3686ae300441c',
        'department': 'Editing',
        'gender': 0,
        'id': 1394953,
        'job': 'Digital Intermediate',
        'name': 'Christine Carr'
    },
    {
        'credit_id': '55402d659251413d6d000249',
        'department': 'Visual Effects',
        'gender': 0,
        'id': 1395269,
        'job': 'Visual Effects Supervisor',

In [28]:
# Creating a fn for crew (director)
def fetch_director(obj):
    array = []
    for i in literal_eval(obj):
        if i['job'] == 'Director':
            array.append(i['name'])
            break
    return array
fetch_director(movies.iloc[0].crew)

['James Cameron']

In [29]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [30]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [31]:
# converting the overviw (str) into list of strings so later we could concatenate with others

movies['overview'] = movies['overview'].apply(lambda x : x.split())

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
# removing spaces in each column
ls = ["genres",'keywords','cast','crew'] 
for element in ls:
    movies[element] = movies[element].apply(lambda x : [i.replace(" ",'') for i in x])

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [35]:
# creating a new column tags and merging the 5 columns

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
new_df = movies[['movie_id','title','tags']]

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [40]:
new_df.tags[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [41]:
# it is recommended to convert the string into lowercase.

new_df['tags'] = new_df.tags.apply(lambda x : x.lower())
new_df.tags[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [42]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [43]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [44]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [45]:
new_df['tags'] = new_df['tags'].apply(stem)

In [46]:
# vectorizing the tags and removing stop words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [47]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [48]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [52]:
# for i in cv.get_feature_names_out():
#     print(i)

cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [54]:
print(similarity.shape)
similarity

(4806, 4806)

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4806, 4806))

In [65]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[
    (1214, np.float64(0.28676966733820225)),
    (2405, np.float64(0.26901379342448517)),
    (3728, np.float64(0.2605130246476754)),
    (507, np.float64(0.255608593705383)),
    (539, np.float64(0.2503866978335957))
]

In [70]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [72]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf